### ISSUE TITLE
Wyeliminowanie prostszych kombinacji wejścia i wyjścia

### ISSUE THREAD

**Issue by Nircek** [Nircek/labirynt#26]
Bardzo często są losowane wejścia i wyjścia blisko siebie, żeby nieco zwiększyć trudność gier, proponuję dopisać linijkę, która by sprawiała, że wyjścia *MUSI* być co najmniej oddalone o pół przekątnej mapy od wyjścia. Jeżeli potrzebujesz inspiracji to to samo zrobiłem w swoim wcześniejszym projekcie labiryntu Nircek/maze@03c84d775c20364a5fa733bebda9b7209a4c94f3.

**Comment by Nircek** [comment]
@Crackhoff postarasz się to zrobić?

**Comment by Crackhoff** [comment]
Rozwiązałem issue #26 commit 1b47201
