### ISSUE TITLE
Dodanie kolorów

### ISSUE THREAD

**Issue by MrDarkness19** [Nircek/labirynt#40]
Przejrzystość w naszym labiryncie jest bardzo słaba i ciężko odróżnić cel i usera od ścian. Trzeba zmienić kolory celu i usera żeby dało się ich odróżnić od ścian i nie oślepnąć od wpatrywania się w hashe.

**Comment by MrDarkness19** [comment]
.

**Comment by Nircek** [comment]
Rozwiązane przez #45

**Comment by Nircek** [comment]
Zmergowane.
