### ISSUE TITLE
Polskie znaki

### ISSUE THREAD

**Issue by MrDarkness19** [Nircek/labirynt#41]
Program posiada polskie znaki. Trzeba je zmienić na zwykłe ( zamiast "ą" wpisać "a" itd. )

**Comment by Nircek** [comment]
TODO: przetestować `chcp 65001` na Windowsach

**Comment by Nircek** [comment]
Testuję na branchu `polskie-znaki`

**Comment by Nircek** [comment]
Rozwiązane na #56.
